---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mas-pg
  namespace: synapse
spec:
  instances: 1
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-prod/synapse/mas-pg
      endpointURL: https://s3.eu-central-1.idrivee2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-credentials
          key: access-key-id
        secretAccessKey:
          name: cnpg-backup-credentials
          key: access-key-secret
    retentionPolicy: "7d"
  bootstrap:
    initdb:
      database: mas
      owner: mas_user
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: true
