---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: synapse-pg
  namespace: synapse
spec:
  instances: 1
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-prod/synapse/synapse-pg
      endpointURL: https://s3.eu-central-1.idrivee2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-credentials
          key: access-key-id
        secretAccessKey:
          name: cnpg-backup-credentials
          key: access-key-secret
  bootstrap:
    initdb:
      database: synapse
      owner: synapse
  storage:
    size: 10Gi
