---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: synapse-external
  namespace: synapse
spec:
  hosts:
  - "justmeowing.net"
  gateways:
  - istio-external-gateway/external-gateway
  http:
  - match:
    - uri:
        prefix: "/_matrix"
    - uri:
        prefix: "/_synapse"
    route:
    - destination:
        host: synapse
        port:
          number: 8008
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: synapse-federation-external
  namespace: synapse
spec:
  hosts:
  - "matrix.justmeowing.net"
  gateways:
  - istio-external-gateway/external-gateway
  http:
    - route:
      - destination:
          host: synapse
          port:
            number: 8008
