apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudnative-pg-dbs
  namespace: cnpg
spec:
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: cloudnative-pg
