deployment:
  strategy: RollingUpdate
  annotateConfigChecksum: true

image:
  repository: twinproduction/gatus

resources:
  requests:
    cpu: 15m
    memory: 25M
  limits:
    memory: 40M

serviceMonitor:
  enabled: false

# Gatus configuration
# ref: https://github.com/TwiN/gatus#configuration
config:
  metrics: true
  endpoints:
    # - name: jkulzer.dev
    #   url: https://jkulzer.dev
    #   interval: 60s
    #   conditions:
    #     - "[STATUS] == 200"
    - name: Authelia
      url: https://auth.jkulzer.dev
      interval: 60s
      conditions:
        - "[STATUS] == 200"
    - name: Immich
      url: https://images.jkulzer.dev
      interval: 60s
      conditions:
        - "[STATUS] == 200"
    - name: Mastodon
      url: https://mastodon.justmeowing.net
      interval: 60s
      conditions:
        - "[STATUS] == 200"
    - name: Element
      url: https://element.justmeowing.net
      interval: 60s
      conditions:
        - "[STATUS] == 200"
    - name: ArgoCD
      url: https://argo.jkulzer.dev
      interval: 60s
      conditions:
        - "[STATUS] == 200"
    - name: Openbao
      url: https://openbao.jkulzer.dev
      interval: 60s
      conditions:
        - "[STATUS] == 200"
    - name: Openspeedtest
      url: https://speedtest.jkulzer.dev
      interval: 60s
      conditions:
        - "[STATUS] == 304"
