---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-pg
  namespace: authelia
spec:
  instances: 1
  bootstrap:
    initdb:
      database: authelia
      owner: authelia
  storage:
    storageClass: ceph-block
    size: 5Gi
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-prod/authelia/authelia-pg
      endpointURL: https://s3.eu-central-1.idrivee2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-credentials
          key: access-key-id
        secretAccessKey:
          name: cnpg-backup-credentials
          key: access-key-secret
    retentionPolicy: "7d"
  monitoring:
    enablePodMonitor: true
