---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ldap
  namespace: authelia
spec:
  sourcePVC: ldap
  trigger:
    schedule: "30 4 * * *" # at 5:30
  rclone:
    rcloneConfigSection: "s3-bucket"
    rcloneDestPath: "prod-backup/authelia/ldap"
    rcloneConfig: "volsync-secret"
    copyMethod: Clone
    volumeSnapshotClassName: csi-rbdplugin-snapshotclass
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authelia-pg-backup
  namespace: authelia
spec:
  schedule: "* 30 4 * * *" # at 5:30
  backupOwnerReference: self
  cluster:
    name: authelia-pg
