{
 "title": "Debugging",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container!=\"\"}",
     "legendFormat": "{{container}}/{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[10m]) * 100) * on(instance) group_left(nodename) (node_uname_info))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{}-ceph_cluster_total_used_bytes{})/ceph_cluster_total_bytes{}",
     "legendFormat": "{{nodename}} - {{device}}"
    }
   ]
  },
  {
   "title": "Unschedulable Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kube_node_spec_unschedulable", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Out of Sync Apps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argocd_app_info{sync_status=\"OutOfSync\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running)",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_job_failed{condition=\"true\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  }
 ]
}