replicaCount: 2

certificate:
  useCertManager: true

# -- Custom environment variables available to webhook
env: {}
  ## -- Vault image
  # VAULT_IMAGE: hashicorp/vault:1.14.8
  # VAULT_CAPATH: /vault/tls

  ## -- Used when the pod that should get secret injected does not specify an imagePullSecret
  # DEFAULT_IMAGE_PULL_SECRET: ""
  # DEFAULT_IMAGE_PULL_SECRET_NAMESPACE: ""
  # DEFAULT_IMAGE_PULL_SECRET_SERVICE_ACCOUNT: ""

  ## -- Define the webhook's timeout for Vault communication, if not defined individually in resources by annotations
  # VAULT_CLIENT_TIMEOUT: "10s"

  ## -- Define the webhook's role in Vault used for authentication, if not defined individually in resources by annotations
  # VAULT_ROLE: ""

  ## -- Cpu requests and limits for init-containers vault-env and copy-vault-env
  # VAULT_ENV_CPU_REQUEST: ""
  # VAULT_ENV_CPU_LIMIT: ""

  ## -- Memory requests and limits for init-containers vault-env and copy-vault-env
  # VAULT_ENV_MEMORY_REQUEST: ""
  # VAULT_ENV_MEMORY_LIMIT: ""

  ## -- Define remote log server for vault-env
  # VAULT_ENV_LOG_SERVER: ""

metrics:
  # -- Enable metrics service for the webhook
  enabled: true
  # -- Metrics service port
  port: 8443
  serviceMonitor:
    # -- Enable service monitor
    enabled: true
    # -- Service monitor scheme
    scheme: https
    tlsConfig:
      # -- Skip TLS checks for service monitor
      insecureSkipVerify: true

rbac:
  psp:
    enabled: false

serviceAccount:
  create: true
