apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: secrets-store-csi-driver
  project: default
  source:
    path: clusters/hybrid01/config/secrets-store-csi-driver
    repoURL: https://github.com/jkulzer/kube
    targetRevision: HEAD
