apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-webhook
  project: default
  source:
    chart: vault-secrets-webhook
    repoURL: oci://ghcr.io/bank-vaults/helm-charts/vault-secrets-webhook
    targetRevision: 8.2.0
    helm:
      releaseName: vault-secrets-webhook
