---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mastodon-ns.yaml
  - mastodon-svc.yaml
  - mastodon-pvc.yaml
  - mastodon-deployment.yaml
  - mastodon-sa.yaml
  - mastodon-dragonfly.yaml
  - mastodon-cnpg.yaml
  - mastodon-virtualservice.yaml
  - mastodon-secret.yaml
  - volsync-secret.yaml
  - cnpg-backup-secret.yaml
  - mastodon-backup.yaml
