---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mastodon
  namespace: mastodon
  labels:
    app: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon
  template:
    metadata:
      labels:
        app: mastodon
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://openbao.openbao.svc.cluster.local:8200"
        vault.security.banzaicloud.io/vault-skip-verify: "false" 
        vault.security.banzaicloud.io/vault-role: "mastodon"
    spec:
      securityContext:
        fsGroup: 991
      serviceAccountName: mastodon-openbao
      initContainers:
      - name: init-db
        image: ghcr.io/mastodon/mastodon:v4.6.3
        command: 
          - "/bin/bash"
        args: 
          - "-c"
          - "bundle exec rails db:setup || true"
        # redirecting failure to /dev/null because it's okay if the init container refuses to init an already existing db
        env:
          - name: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
            value: vault:kvv2/data/mastodon#ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
          - name: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
            value: vault:kvv2/data/mastodon#ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
          - name: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
            value: vault:kvv2/data/mastodon#ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
          - name: SECRET_KEY_BASE
            value: vault:kvv2/data/mastodon#SECRET_KEY_BASE
          - name: REDIS_HOST
            value: dragonfly-mastodon.mastodon.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            value: vault:kvv2/data/mastodon#dragonfly-password
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: mastodon-pg-app
                key: fqdn-uri
      containers:
      - name: mastodon
        image: ghcr.io/mastodon/mastodon:v4.6.3
        command: 
        - "bundle"
        args:
        - "exec"
        - "rails"
        - "server"
        env:
          - name: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
            value: vault:kvv2/data/mastodon#ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
          - name: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
            value: vault:kvv2/data/mastodon#ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
          - name: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
            value: vault:kvv2/data/mastodon#ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
          - name: SECRET_KEY_BASE
            value: vault:kvv2/data/mastodon#SECRET_KEY_BASE
          - name: REDIS_HOST
            value: "dragonfly-mastodon.mastodon.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            value: vault:kvv2/data/mastodon#dragonfly-password
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: mastodon-pg-app
                key: fqdn-uri
          - name: OIDC_ENABLED
            value: "true"
          - name: OIDC_DISPLAY_NAME
            value: "Authelia"
          - name: "OIDC_DISCOVERY"
            value: "true"
          - name: "OIDC_ISSUER"
            value: "https://auth.justmeowing.net"
          - name: "OIDC_SCOPE"
            value: "openid,profile,email,mastodon-username"
          - name: "OIDC_UID_FIELD"
            value: "mastodon-username"
          - name: "OIDC_CLIENT_ID"
            value: "mastodon"
          - name: "OIDC_CLIENT_SECRET"
            value: "vault:kvv2/data/mastodon#OIDC_CLIENT_SECRET"
          - name: "OIDC_REDIRECT_URI"
            value: "https://mastodon.justmeowing.net/auth/auth/openid_connect/callback"
          - name: "OIDC_SECURITY_ASSUME_EMAIL_IS_VERIFIED"
            value: "true"
          - name: "ONE_CLICK_SSO_LOGIN"
            value: "true"
          - name: "OMNIAUTH_ONLY"
            value: "true"
          - name: "ALLOW_UNSAFE_AUTH_PROVIDER_REATTACH"
            value: "true"
          - name: "LOCAL_DOMAIN"
            value: "justmeowing.net"
          - name: "WEB_DOMAIN"
            value: "mastodon.justmeowing.net"
          - name: "SINGLE_USER_MODE"
            value: "true"
        ports:
        - name: mastodon
          protocol: TCP
          containerPort: 3000
        volumeMounts:
        - name: mastodon-media
          mountPath: /opt/mastodon/public/system
      volumes:
      - name: mastodon-media
        persistentVolumeClaim:
          claimName: mastodon-media
