---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: mastodon-pg-backup
  namespace: mastodon
spec:
  schedule: "30 2 * * * *" # at 3:30
  backupOwnerReference: self
  cluster:
    name: mastodon-pg
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mastodon-media
  namespace: mastodon
spec:
  sourcePVC: mastodon-media
  trigger:
    schedule: "30 2 * * *" # at 3:30
  rclone:
    rcloneConfigSection: "s3-bucket"
    rcloneDestPath: "prod-backup/mastodon/mastodon-media"
    rcloneConfig: "volsync-secret"
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-rbdplugin-snapshotclass
