# config -- The [polaris configuration](https://github.com/FairwindsOps/polaris#configuration). If not provided then the [default](https://github.com/FairwindsOps/polaris/blob/master/examples/config.yaml) config from Polaris is used.
config: null

# additionalExemptions -- List of additional exemptions to append to the exemptions given in `config`
additionalExemptions: null

# mergeConfig -- If the config should be merged with the default config. See https://github.com/FairwindsOps/polaris/pull/1075
mergeConfig: false


image:
  repository: us-docker.pkg.dev/fairwinds-ops/oss/polaris

rbac:
  enabled: true

templateOnly: false

dashboard:
  enable: true
  port: 8080
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 500Mi

webhook:
  # webhook.enable -- Whether to run the webhook
  enable: false
  # webhook.validate -- Enables the Validating Webhook, to reject resources with issues
  validate: true
  # webhook.mutate -- Enables the Mutating Webhook, to modify resources with issues
  mutate: false
  # webhook.replicas -- Number of replicas
  replicas: 2
  # webhook.logLevel -- Set the logging level for the Webhook command
  logLevel: info
