---
apiVersion: v1
kind: ConfigMap
metadata:
  name: well-known
  namespace: well-known-justmeowing-net
data:
  default.conf: |-
    server {
      listen       80;

      location / {
        return 501;
      }

      location /.well-known/matrix/server {
        access_log /dev/stdout;
        add_header Access-Control-Allow-Origin *;
        default_type application/json;
        return 200 '{"m.server": "matrix.justmeowing.net:443"}';
      }

      location /.well-known/matrix/client {
        access_log /dev/stdout;
        add_header Access-Control-Allow-Origin *;
        default_type application/json;
        return 200 '{"m.homeserver": {"base_url": "https://justmeowing.net"}, "org.matrix.msc2965.authentication": {"issuer": "https://matrixauth.justmeowing.net", "account": "https://matrixauth.justmeowing.net"}}';
      }
      location /.well-known/webfinger {
        access_log /dev/stdout;
        add_header Access-Control-Allow-Origin '*';
        return 301 https://mastodon.justmeowing.net$request_uri;
      }
      location /.well-known/host-meta {
        access_log /dev/stdout;
        add_header Access-Control-Allow-Origin '*';
        default_type application/xrd+xml;
        return 200 '<?xml version="1.0" encoding="UTF-8"?><XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0"><Link rel="lrdd" template="https://mastodon.justmeowing.net/.well-known/webfinger?resource={uri}"/></XRD>';
      }
    }
