---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly-immich
  namespace: immich
spec:
  replicas: 1
  args:
    - --maxmemory=1000M
    - --proactor_threads=2
    - --default_lua_flags=allow-undeclared-keys
  authentication:
    passwordFromSecret:
      name: immich-dragonfly-secret
      key: password
  resources:
    requests:
      cpu: 25m
      memory: 100M
    limits:
      memory: 1500M
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-dragonfly-secret
  namespace: immich
  annotations:
    vault.security.banzaicloud.io/vault-addr: "http://openbao.openbao.svc.cluster.local:8200" # optional, the address of the Vault service, default values is https://vault:8200
    vault.security.banzaicloud.io/vault-role: "default" # optional, the default value is the name of the ServiceAccount the Pod runs in, in case of Secrets and ConfigMaps it is "default"

data:
  password: dmF1bHQ6a3Z2Mi9kYXRhL2ltbWljaCNkcmFnb25mbHktcGFzc3dvcmQ=
