global:
  enabled: true
  namespace: "openbao"
  serverTelemetry:
    prometheusOperator: true

injector:
  enabled: true
  metrics:
    enabled: true
  agentDefaults:
    cpuLimit: "500m"
    cpuRequest: "250m"
    memLimit: "128Mi"
    memRequest: "64Mi"
    template: "map"
  authPath: "auth/kubernetes"

server:
  enabled: true
  resources: {}
  # resources:
  #   requests:
  #     memory: 256Mi
  #     cpu: 250m
  #   limits:
  #     memory: 256Mi
  #     cpu: 250m

  # authDelegator enables a cluster role binding to be attached to the service
  # account.  This cluster role binding can be used to setup Kubernetes auth
  # method. See https://openbao.org/docs/auth/kubernetes
  authDelegator:
    enabled: true

  service:
    enabled: true
    extraPorts:
      - name: server
        port: 8202
        targetPort: 8202

  extraPorts:
  - containerPort: 8202
    name: server

  livenessProbe:
    enabled: false
    # Used to define a liveness exec command. If provided, exec is preferred to httpGet (path) as the livenessProbe handler.
    execCommand: []
    # - /bin/sh
    # - -c
    # - /openbao/userconfig/mylivenessscript/run.sh
    # Path for the livenessProbe to use httpGet as the livenessProbe handler
    path: "/v1/sys/health?standbyok=true"
    # Port number on which livenessProbe will be checked if httpGet is used as the livenessProbe handler
    port: 8202
    # When a probe fails, Kubernetes will try failureThreshold times before giving up
    failureThreshold: 2
    # Number of seconds after the container has started before probe initiates
    initialDelaySeconds: 60
    # How often (in seconds) to perform the probe
    periodSeconds: 5
    # Minimum consecutive successes for the probe to be considered successful after having failed
    successThreshold: 1
    # Number of seconds after which the probe times out.
    timeoutSeconds: 3

  # This configures the OpenBao Statefulset to create a PVC for data
  # storage when using the file or raft backend storage engines.
  # See https://openbao.org/docs/configuration/storage to know more
  dataStorage:
    enabled: true
    size: 10Gi
  # Run OpenBao in "standalone" mode. This is the default mode that will deploy if
  # no arguments are given to helm. This requires a PVC for data storage to use
  # the "file" backend.  This mode is not highly available and should not be scaled
  # past a single replica.
  standalone:
    enabled: true

    # config is a raw string of default configuration when using a Stateful
    # deployment. Default is to use a PersistentVolumeClaim mounted at /openbao/data
    # and store data there. This is only used when using a Replica count of 1, and
    # using a stateful set. This should be HCL.

    # Note: Configuration files are stored in ConfigMaps so sensitive data
    # such as passwords should be either mounted through extraSecretEnvironmentVars
    # or through a Kube secret.  For more information see:
    # https://openbao.org/docs/platform/k8s/helm/run/#protecting-sensitive-openbao-configurations
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8202"
        cluster_address = "[::]:8201"
        # Enable unauthenticated metrics access (necessary for Prometheus Operator)
      }

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        telemetry {
         unauthenticated_metrics_access = "true"
         metrics_only = "true"
        }
      }

      storage "file" {
        path = "/openbao/data"
      }

# OpenBao UI
ui:
  # True if you want to create a Service entry for the OpenBao UI.
  #
  # serviceType can be used to control the type of service created. For
  # example, setting this to "LoadBalancer" will create an external load
  # balancer (for supported K8S installations) to access the UI.
  enabled: true
  publishNotReadyAddresses: true


csi:
  # -- True if you want to install an openbao-csi-provider daemonset.
  #
  # Requires installing the secrets-store-csi-driver separately, see:
  # https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation
  #
  # With the driver and provider installed, you can mount OpenBao secrets into volumes
  # similar to the OpenBao Agent injector, and you can also sync those secrets into
  # Kubernetes secrets.
  enabled: false

# OpenBao is able to collect and publish various runtime metrics.
# Enabling this feature requires setting adding `telemetry{}` stanza to
# the OpenBao configuration. There are a few examples included in the `config` sections above.
#
# For more information see:
# https://openbao.org/docs/configuration/telemetry
# https://openbao.org/docs/internals/telemetry
serverTelemetry:
  # Enable support for the Prometheus Operator. If authorization is not required for
  # OpenBao's metrics endpoint, the following OpenBao server `telemetry{}` config must be included
  # in the `listener "tcp"{}` stanza
  #  telemetry {
  #    unauthenticated_metrics_access = "true"
  #  }
  #
  # See the `standalone.config` for a more complete example of this.
  #
  # In addition, a top level `telemetry{}` stanza must also be included in the OpenBao configuration:
  #
  # example:
  #  telemetry {
  #    prometheus_retention_time = "30s"
  #    disable_hostname = true
  #  }
  #
  # Configuration for monitoring the OpenBao server.
  serviceMonitor:
    enabled: true
    port: "metrics"

  prometheusRules:
    # The Prometheus operator *must* be installed before enabling this feature,
    # if not the chart will fail to install due to missing CustomResourceDefinitions
    # provided by the operator.

    # Deploy the PrometheusRule custom resource for AlertManager based alerts.
    # Requires that AlertManager is properly deployed.
    enabled: true

    # Selector labels to add to the PrometheusRules.
    # When empty, defaults to:
    #  release: prometheus
    selectors: {}

    # Some example rules.
    rules: []
    #  - alert: vault-HighResponseTime
    #    annotations:
    #      message: The response time of OpenBao is over 500ms on average over the last 5 minutes.
    #    expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 500
    #    for: 5m
    #    labels:
    #      severity: warning
    #  - alert: vault-HighResponseTime
    #    annotations:
    #      message: The response time of OpenBao is over 1s on average over the last 10 minutes.
    #    expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 1000
    #    for: 10m
    #    labels:
    #      severity: critical
